### ISSUE TITLE
【Feature Request】support zip file upload

### ISSUE THREAD

**Issue by tabs** [ninoseki/eml_analyzer#128]
Why not consider adding compressed file uploads later, analyzing multiple .eml files in batches, and supporting historical query viewing. Your project is great, I gave you stars.

**Comment by tabs** [comment]
I have a project requirement. I need to upload and analyze multiple .eml files in batches, and support direct relationship analysis of contacts, terrorism, and early warning analysis of child trafficking. I hope to get your help in the future.

**Comment by ninoseki** [comment]
Sorry, I don't have a plan (or willingness) to implement the idea you suggested.
The app has REST API and you can automate the task you wanted with the API. That's enough IMHO.

**Comment by tabs** [comment]
> Sorry, I don't have a plan (or willingness) to implement the idea you suggested.
> The app has REST API and you can automate the task you wanted with the API. That's enough IMHO.

Anyway, thank you for your help with your project.
