### ISSUE TITLE
Old header from value when checking multiple emails in a row

### ISSUE THREAD

**Issue by wornet-aer** [ninoseki/eml_analyzer#134]
When analyzing multiple emails within the same "session" (without doing a browser reload), the Header-From value always contains the sender of the first email which has been uploaded.

After doing a short debugging dive, it looks like the from header value gets correctly reported by the backend as a response to the check request, but isn't refreshed within the frontend.

**Comment by ninoseki** [comment]
Thank you for reporting the issue. I just fixed it by #136.
