### ISSUE TITLE
Docker image creation error

### ISSUE THREAD

**Issue by sephirothac** [ninoseki/eml_analyzer#145]
Hello, when creating the image docker I have an error on the cmd sa-update

docker build . -t eml_analyzer

Step 7/19 : RUN sa-update -v
 ---> Running in a55a09bcf8fc
Update available for channel updates.spamassassin.org: -1 -> 1898171
http: (lwp) GET http://spamassassin.apache.org/updates/MIRRORED.BY, 200 OK
http: (lwp) GET http://www.sa-update.pccc.com/1898171.tar.gz, 200 OK
http: (lwp) GET http://www.sa-update.pccc.com/1898171.tar.gz.sha512, 200 OK
http: (lwp) GET http://www.sa-update.pccc.com/1898171.tar.gz.sha256, 200 OK
http: (lwp) GET http://www.sa-update.pccc.com/1898171.tar.gz.asc, 200 OK
config: invalid regexp for __URI_TRY_3LD 'm,^https?://(?:try(?!r\.codeschool)|start|get(?!\.adobe)|save|check(?!out)|act|compare|join|learn(?!ing)|request|visit(?!or|\.vermont)|my(?!sub|turbotax|news\.apple|a\.godaddy|account|support|build|blob)\w)[^.]*\.[^/]+\.(?<!list-manage\.)(?:com|net)\b,i': Variable length lookbehind not implemented in regex m/(?i)^https?://(?:try(?!r\.codeschool)|start|get(?!\.adobe)|save|check(?!out)|act|compare|join|learn(?!ing)|request|vi.../
channel: lint check of update failed, channel failed
Update failed, exiting with code 4
The command '/bin/sh -c sa-update -v' returned a non-zero code: 4

Thank you for your contribution and your help.

**Comment by sephirothac** [comment]
for the moment it solves my problem

sa-update --checkonly -v

**Comment by ninoseki** [comment]
https://groups.google.com/g/linux.debian.bugs.dist/c/Jqf31WJcIcg

**Comment by ninoseki** [comment]
It is SpamAssasin issue and it will be fixed soon.
