### ISSUE TITLE
GitHub Issue: EML Analyzer - Error in Date Parsing

### ISSUE THREAD

**Issue by mbenecke** [ninoseki/eml_analyzer#191]
**Description:**

After cloning the main branch of the EML Analyzer repository and adding the VirusTotal API key, I encountered an issue while running the Docker container. The application seems to start successfully, but when making a POST request to analyze an EML file, a 500 Internal Server Error occurs. The error trace indicates a problem in the date parsing process.

**Steps to Reproduce:**

1. Clone the main branch of the EML Analyzer repository.
2. Add the VirusTotal API key to the appropriate environment variable.
3. Run the application using `docker-compose up`.
4. Make a POST request to analyze an EML file.

**Expected Behavior:**

The application should successfully analyze the EML file and return the appropriate response.

**Actual Behavior:**

The application returns a 500 Internal Server Error, and the error trace indicates a TypeError related to date parsing.

**Error Trace:**

```plaintext
...
eml_analyzer_1  | TypeError: Cannot parse argument of type None.
...
```

**Environment:**

- Operating System: Ubuntu 22.04.3
- Docker Version: [Docker version 20.10.18, build b40c2f6]

**Additional Information:**
VirusTotal API Key has been added to the environment variables.
The issue seems to be related to date parsing in the EML file processing.
It happens with several eml and msg files, it seems unrelated to the Target.

**Note:**

I have verified that this issue occurs consistently in the provided environment. Any assistance in resolving this issue would be highly appreciated.

**Comment by ninoseki** [comment]
Thank you for reporting. I'd appreciate if you could provide an EML file to reproduce the issue. (Please anonymize sensitive data in it)

**Comment by ninoseki** [comment]
I will close this issue if there is no response for a week.
