### ISSUE TITLE
Enabling SSL Support

### ISSUE THREAD

**Issue by kraken8585** [ninoseki/eml_analyzer#196]
Hi,

How do we enable SSL for the deployed instance?

**Comment by ninoseki** [comment]
This project supports Heroku deployment and Heroku offers SSL by default.
If you want to deploy this project in another platform, please set a load balancer or reverse proxy to use SSL.

**Comment by kraken8585** [comment]
Adding use_ssl to true and referecing the certificates in circus.ini, would
that work?
