### ISSUE TITLE
Can't copy extracted URL

### ISSUE THREAD

**Issue by catalingiana** [ninoseki/eml_analyzer#213]
Hello, I've tried to copy the extracted URL, but it looks that I only have the possibility to send it to VT or other providers. Sometimes the URLs contain sensitive info and I would like to remove it before uploading it to external scanners.
Is there any way to do that?

Thanks!

**Comment by ninoseki** [comment]
Thanks for a good suggestion. I added a dropdown item to copy a value to the clipboard.

**Comment by catalingiana** [comment]
Thanks for updating the tool!

Sent from Yahoo Mail on Android 
 
  On Wed, Feb 28, 2024 at 12:34, Manabu ***@***.***> wrote:   


Thanks for a good suggestion. I added a dropdown item to copy a value to the clipboard. (#215)
