### ISSUE TITLE
Cannot change source port for eml analyzer

### ISSUE THREAD

**Issue by binary-sh** [ninoseki/eml_analyzer#224]
Hello,

I am using portainer which already has the host port 8000 allocated. I tried changing all port values from your tool: 8000 -> 8005 but the tool does not spin up after this. Any advice?

**Comment by ninoseki** [comment]
Pass `PORT` env like ` docker run -e PORT=8181`. 
Also I don't know anything about "portainer". Please ask a question to that platform about the configuration. It's not my job.
