### ISSUE TITLE
Unable to extract URL from eml content

### ISSUE THREAD

**Issue by milannshrestha** [ninoseki/eml_analyzer#42]
Hey,

In section **Extracted URLs**, there are options for url lookup to VirusTotal, UrlScan.io and Browserling.  So, the eml that has following content url, 
![image](https://user-images.githubusercontent.com/31887847/91143006-8ad52800-e6d1-11ea-8cd0-4fbbb8e1b13c.png)

Following was the result of extracted URL which is not proper query format for mentioned URL scanner. That is, the marked values are considered as the part of embedded url. 

![untitled(1)](https://user-images.githubusercontent.com/31887847/91143453-48f8b180-e6d2-11ea-8ec5-34972e23ddc6.png)

For eg.
![image](https://user-images.githubusercontent.com/31887847/91143535-675ead00-e6d2-11ea-900e-5fa76e1efaf3.png)

Thank You.

**Comment by ninoseki** [comment]
@milannshrestha Could you make an issue at [fhightower/ioc-finder](https://github.com/fhightower/ioc-finder), please?
It is because EML analyzer internally uses ioc-finder to extract IoCs (including URLs) from a block of text.
