### ISSUE TITLE
Is there a file size limit?

### ISSUE THREAD

**Issue by andreas5232** [ninoseki/eml_analyzer#56]
When uploading a 15 megabytes large eml file, I'm getting an empty response from the API.

The POST request to /api/analyze/file is sent, but after some time 0 B are returned and the loading circle in the GUI just disappears.

Please let me know if you need further details.

**Comment by ninoseki** [comment]
@andreas5232 Cloud you share the file with me, please?
Here is my contact address.
https://flowcrypt.com/pub/manabu.niseki@gmail.com
You can use PGP if you want to use it.

**Comment by ninoseki** [comment]
I checked the eml file and it is possible to analyze the file in my local env.
Note that eml-analyzer.herokuapp.com uses a Heroku's free dyno. So a CPU/memory heavy task is cannot executed in it.
Please consider to use the app in your local env. It is the straightforward solution for the issue.

**Comment by andreas5232** [comment]
That's strange, I'm already using a local docker env deployed using the guide specified in the readme. Do I have to increase any limits?

**Comment by ninoseki** [comment]
Sorry I tested it in the my laptop without docker and it did not work in the docker container as you said.
I cannot understand the root cause but it seems like an issue is lying on a combination of supervisor and gunicorn.
So I replaced supervisor + gunicorn with circus + uvicorn and the combination works fine.

**Comment by ninoseki** [comment]
@andreas5232 Could you git pull the repository again and test it, please?

**Comment by andreas5232** [comment]
Thank you for the fast response!
I have pulled and redeployed the docker container. 
Now it loads the large eml file fine. 🎉 👍 

One thing I'm still wondering about are the displayed attachment file sizes.
My computer says the eml has: 16.198.857 Bytes.
However the eml analyzer displays 17 attachments for this email with 16 times 15.4 Mb and one with 11.4 Mb. 
That doesn't seem realistic to me.

**Comment by ninoseki** [comment]
@andreas5232 Just a confirmation, is your eml file a real world one? Or is it manipulated/crafted one?

**Comment by andreas5232** [comment]
The eml file is a real world scenario, which I found during my daily work as spamfilter admin.

**Comment by ninoseki** [comment]
Fixed. #59
