### ISSUE TITLE
Uploading to VirusTotal

### ISSUE THREAD

**Issue by timtheresearcher** [ninoseki/eml_analyzer#76]
Where do I add my VT API key so that I can upload attachments to VT?

**Comment by nickjcoco** [comment]
Not sure if you still need this answer since this issue is quite old, but might help anyone in the future who needs it.

I put my API key in the /app/core/settings.py file, line 22, then built the image and ran the container.

```
VIRUSTOTAL_API_KEY: Secret = config("VIRUSTOTAL_API_KEY", cast=Secret, default="$API_KEY_HERE")
```

**Comment by ninoseki** [comment]
- There is no feature to upload an attachment to VirusTotal
- You can set VirusTotal API key via an environmental variable `VIRUSTOTAL_API_KEY`. It is used for a hash lookup.
